### ISSUE TITLE
Make `utils.pack` work with empty buffer

### ISSUE THREAD

**Issue by aleclarson** [Simonwep/nason#11]
Right now, passing an empty buffer to `utils.pack` results in this error:
```
RangeError: Invalid typed array length: -Infinity
```

**Comment by simonwep** [comment]
Fixed, vailable in [v1.3.1](https://github.com/Simonwep/nason/releases/tag/1.3.1) :)

**Comment by aleclarson** [comment]
Hot damn, thanks Simon 🎉 

..and thanks for the float encoder!!
