### ISSUE TITLE
Floating point support

### ISSUE THREAD

**Issue by aleclarson** [Simonwep/nason#4]
Hi @Simonwep, can you explain the problems you've had with implementing float support?

**Comment by simonwep** [comment]
Hey :) I believe it was about precision back then. I guess the number could be stored as two integers and put back together when de-serializing 🤔

**Comment by aleclarson** [comment]
I have zero experience in binary packing, but does this code help you at all?

http://jsfromhell.com/classes/binary-parser
(Specifically the `encodeFloat` and `decodeFloat` functions)

**Comment by simonwep** [comment]
_jsfromhell.com_ - that domain name describes the code pretty well 😂
I might give it a try on the next weekend though, let's see what I can do :)

**Comment by aleclarson** [comment]
Did you ever give this a shot? 🤞

**Comment by simonwep** [comment]
Hey :) I'm currently pretty much busy, I'll keep this in mind and ping you here asap when I tried it!

**Comment by simonwep** [comment]
Added in f83d24c2357c06975bbed7fa68a5e3113fba2ef9, available in [v1.3](https://github.com/Simonwep/nason/releases/tag/1.3.0) :)
